# Generated by Django 4.2.5 on 2023-10-10 17:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_inquiries', '0003_rename_message_reply_reply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reply',
            new_name='Replie',
        ),
    ]
