# Generated by Django 4.2.5 on 2023-10-11 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_inquiries', '0005_alter_post_message'),
        ('facilitators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='get_message',
            name='reply',
        ),
        migrations.AlterField(
            model_name='get_message',
            name='message',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='get_message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FacPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_replies', to='student_inquiries.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_facposts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
